package com.example.asiceverifier;

public enum Errors {
    ASICE_OPEN_FAILED,
    SIGNATURE_XML_NOT_FOUND,
    SIGNATURE_XML_PARSE_FAILED,

    PROFILE_SIGNATUREVERSION_MISSING,
    PROFILE_SIGNATUREVERSION_NAMESPACE_UNSUPPORTED,
    PROFILE_DS_PREFIX_MISSING_ON_SIGNATURE,

    PROFILE_XADESSIGNATURE_MISSING,
    PROFILE_ASIC_NAMESPACE_MISSING,
    PROFILE_ASIC_NAMESPACE_UNSUPPORTED,

    XMLSIG_SIGNATURE_ELEM_MISSING,
    XMLSIG_SIGNEDINFO_MISSING,
    XMLSIG_SIGNATUREVALUE_MISSING,

    XMLSIG_C14N_METHOD_MISSING,
    XMLSIG_C14N_ALGO_UNSUPPORTED,

    XMLSIG_SIGNATURE_METHOD_MISSING,
    XMLSIG_SIGNATURE_ALGO_UNSUPPORTED,

    XMLSIG_REFERENCE_MISSING,
    XMLSIG_DIGEST_METHOD_MISSING,
    XMLSIG_DIGEST_ALGO_UNSUPPORTED,
    XMLSIG_X509DATA_CONTENT_INVALID,
    XMLSIG_REFERENCE_MISSING_ID,

    XMLSIG_TRANSFORMS_MISSING,
    CERTIFICATE_MISSING,
    XMLSIG_TRANSFORM_ALGO_UNSUPPORTED,

    XMLSIG_KEYINFO_MISSING,
    XMLSIG_KEYINFO_INVALID,

    XMLSIG_DIGESTVALUE_INVALID,
    XMLSIG_SIGNATUREVALUE_INVALID,
    XMLSIG_CORE_VALIDATION_ERROR,

    TIMESTAMP_MISSING,
    TIMESTAMP_EMPTY,
    TIMESTAMP_CERT_INVALID,
    TIMESTAMP_MESSAGEIMPRINT_INVALID,
    TIMESTAMP_INVALID,

    // 2c
    XMLSIG_SIGNATURE_ID_MISSING,
    XMLSIG_SIGNATUREVALUE_ID_MISSING,
    XMLSIG_REFERENCE_TYPE_KEYINFO_INVALID,
    XMLSIG_REFERENCE_TYPE_SIGPROPS_INVALID,
    XMLSIG_REFERENCE_TYPE_SIGNEDPROPS_INVALID,
    XMLSIG_REFERENCE_TYPE_NOT_ALLOWED,
    XMLSIG_KEYINFO_ID_MISSING,
    XMLSIG_X509DATA_MISSING,
    XMLSIG_X509_ISSUER_MISMATCH,
    XMLSIG_X509_SUBJECT_MISMATCH,
    XMLSIG_X509DATA_DECODE_ERROR,
    XMLSIG_SIGNATUREPROPERTIES_MISSING,
    XMLSIG_SIGNATUREPROPERTIES_ID_MISSING,
    XMLSIG_SIGNATUREPROPERTIES_COUNT_INVALID,
    XMLSIG_SIGNATUREPROPERTY_TARGET_INVALID,
    XMLSIG_REFERENCE_URI_EMPTY,
    XMLSIG_REFERENCE_URI_NOT_FOUND,

    // 3a
    CERTIFICATE_REVOKED, UNKNOWN_ERROR, XADES_MISSING_MIME_TYPE, XADES_MISSING_DATA_OBJECT_FORMAT, CERTIFICATE_EXPIRED_AT_T

}
