package com.example.asiceverifier;

public enum Errors {
    ASICE_OPEN_FAILED,
    SIGNATURE_XML_NOT_FOUND,
    SIGNATURE_XML_PARSE_FAILED,

    PROFILE_SIGNATUREVERSION_MISSING,
    PROFILE_SIGNATUREVERSION_NAMESPACE_UNSUPPORTED,
    PROFILE_DS_PREFIX_MISSING_ON_SIGNATURE,

    PROFILE_XADESSIGNATURE_MISSING,
    PROFILE_ASIC_NAMESPACE_MISSING,
    PROFILE_ASIC_NAMESPACE_UNSUPPORTED,

    XMLSIG_SIGNATURE_ELEM_MISSING,
    XMLSIG_SIGNEDINFO_MISSING,
    XMLSIG_SIGNATUREVALUE_MISSING,

    XMLSIG_C14N_METHOD_MISSING,
    XMLSIG_C14N_ALGO_UNSUPPORTED,

    XMLSIG_SIGNATURE_METHOD_MISSING,
    XMLSIG_SIGNATURE_ALGO_UNSUPPORTED,

    XMLSIG_REFERENCE_MISSING,
    XMLSIG_DIGEST_METHOD_MISSING,
    XMLSIG_DIGEST_ALGO_UNSUPPORTED,

    XMLSIG_TRANSFORMS_MISSING,
    XMLSIG_TRANSFORM_ALGO_UNSUPPORTED,

    XMLSIG_KEYINFO_MISSING,
    XMLSIG_KEYINFO_INVALID,

    XMLSIG_DIGESTVALUE_INVALID,
    XMLSIG_SIGNATUREVALUE_INVALID,
    XMLSIG_CORE_VALIDATION_ERROR,

    TIMESTAMP_MISSING,
    TIMESTAMP_EMPTY,
    TIMESTAMP_CERT_INVALID,
    TIMESTAMP_MESSAGEIMPRINT_INVALID,
    TIMESTAMP_INVALID
}
